### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by arpitnot4u** [mjbright/futurelearn-dl#1]
OS: Ubuntu 14.04
Python: 3

the course that I'm trying to download: https://www.futurelearn.com/courses/ageing/1/todo

gar@gar-B85M:~/Downloads/futurelearn-dl-master$ python futurelearn-dl.py myEmailId MyPassword ageing 1
Downloading course 'ageing' - seems to comprise of 6 weeks
Traceback (most recent call last):
  File "futurelearn-dl.py", line 552, in <module>
    getCourseWeekStepPage(course_id, week_id, step_id, week_num)
  File "futurelearn-dl.py", line 226, in getCourseWeekStepPage
    getDownloadableURLs(course_id, week_id, step_id, week_num, content, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 359, in getDownloadableURLs
    downloadFile(url, download_dir, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 419, in downloadFile
    downloadURLToFile(url, ofile, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 370, in downloadURLToFile
    debug(1, "Downloading url<{}> ...".format(url), end='')
TypeError: debug() got an unexpected keyword argument 'end'
gar@gar-B85M:~/Downloads/futurelearn-dl-master$ 

gar@gar-B85M:~/Downloads/futurelearn-dl-master$ python futurelearn-dl.py myEmailId MyPassword ageing 1 1
Downloading course 'ageing' - seems to comprise of 6 weeks
Downloading week 1
Downloading available week1 material
Traceback (most recent call last):
  File "futurelearn-dl.py", line 563, in <module>
    getCourseWeekStepPage(course_id, week_id, step_id, week_num)
  File "futurelearn-dl.py", line 226, in getCourseWeekStepPage
    getDownloadableURLs(course_id, week_id, step_id, week_num, content, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 359, in getDownloadableURLs
    downloadFile(url, download_dir, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 419, in downloadFile
    downloadURLToFile(url, ofile, DOWNLOAD_TYPE)
  File "futurelearn-dl.py", line 370, in downloadURLToFile
    debug(1, "Downloading url<{}> ...".format(url), end='')
TypeError: debug() got an unexpected keyword argument 'end'
gar@gar-B85M:~/Downloads/futurelearn-dl-master$ 

my python version 

gar@gar-B85M:~/Downloads/futurelearn-dl-master$ python
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

Let me know if I'm going wrong.

**Comment by mjbright** [comment]
Sorry, I see there's a bug on my side ... I'm afraid I have v. limited
internet for the next 2 weeks.
Will fix as soon as I'm back.

**Comment by mjbright** [comment]
Hi, back from holiday ... I've just submitted the fix for this.
Thanks a lot for trying out futurelearn-dl, I hope it's useful.
