### ISSUE TITLE
license missing

### ISSUE THREAD

**Issue by dpshelio** [mjbright/futurelearn-dl#12]
Hi! Thanks for sharing your code on github, however I'm afraid as it's now I wouldn't be able to use it or improve it. As it is @mjbright owns the copyright of this implementation. Please, consider adding a license file - [github makes the process very easy](https://help.github.com/articles/adding-a-license-to-a-repository/).

**Comment by mjbright** [comment]
Thanks for your suggestion, you're right I should put a license.

GPL3 license added with commit af61719be77f3290f60de36b7018daa79b6464ac.
