### ISSUE TITLE
FATAL:No quote(char=\) in <<o <a href=\"http://w...>>

### ISSUE THREAD

**Issue by zenny** [mjbright/futurelearn-dl#13]
New issue with https://www.futurelearn.com/courses/ancient-health/6/todo/49272:

```
FATAL:No quote(char=\) in <<o <a href=\"http://w...>>
```

With other courses working alright.

Cheers,
/z

**Comment by zenny** [comment]
Hi,

This script is wonderful, but gives different errors at different times. 

For example, I tried the ancient-health again a while ago (see timestamps from the bash prompt and it reported:

```
2019-07-11 09:09:57 zenny@MACHINE: $ /usr/bin/python3 futurelearn-dl.py EMAIL PASSWORD ancient-health 6
Traceback (most recent call last):
  File "futurelearn-dl.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

It is not absence of 'request' module either as evident from:

```
2019-07-11 09:18:30 zenny@MACHINE: $ sudo pip3 install requests
Requirement already satisfied (use --upgrade to upgrade)
Cleaning up...
```

However, I tried again after a while and it worked without a glitch without me doing anything on my part or in the machine related to python and related modules installation:

```
2019-07-11 09:27:06 zenny@MACHINE: $ python3 futurelearn-dl.py EMAIL PASSWORD ancient-health 6
Downloading 6-week course 'ancient-health'
Downloading url<https://view.vzaar.com/9028692/video>
	to file <ancient-health/week1/1.1-Images-of-health_9028692.mp4> ...
type=mp4, content.len=31012405
Downloading url<https://view.vzaar.com/9045066/video>
	to file <ancient-health/week1/1.2-How-healthy-are-you_9045066.mp4> ...
...
Downloading url<https://view.vzaar.com/9030981/video>
	to file <ancient-health/week6/6.18-Caerleon_9030981.mp4> ...
type=mp4, content.len=13143860
```
On times it downloads only a portion as reported at https://github.com/mjbright/futurelearn-dl/issues/8#issuecomment-507018611.

Could not figure out exactly what happens on times, it could be upstream or something else!? Just curious.

Cheers,
/z

**Comment by mjbright** [comment]
Thanks for these comments.

I don't have time to look right now but will try to a bit later.

**Comment by zenny** [comment]
@mjbright  Thanks.

Reporting the same issue today with https://www.futurelearn.com/courses/back-skills-training-programme/2/

```
2019-07-17 22:59:49 zenny@MACHINE: $ ./TEST_futurelearn-dl.py.sh
Downloading 6-week course 'back-skills-training-programme'
FATAL:No quote(char=\) in <<t;<a href=\"https://...>>
```

But the error may go away if I run again in a day or two, fyi. Shall update when it works, just reporting for your attention.

UPDATE: I tried once again (see timestamps), but after downloading partially, it defaulted back to the same error after downloading a single file:

```
2019-07-20 17:51:01 zenny@MACHINE:[~/Downloads/FutureLearn/futurelearn-dl]:$ ./TEST_futurelearn-dl.py.sh
Downloading 6-week course 'back-skills-training-programme'
Downloading url<https://view.vzaar.com/18055652/video>
	to file <back-skills-training-programme/week1/2.11-Using-exploring-questions_18055652.mp4> ...
type=mp4, content.len=26387784
Downloading url<https://view.vzaar.com/18390529/video>
	to file <back-skills-training-programme/week1/2.13-Dealing-with-distress_18390529.mp4> ...
type=mp4, content.len=10258922
FATAL:No quote(char=\) in <<t;<a href=\"https://...>>
```

**Comment by zenny** [comment]
This https://github.com/mjbright/futurelearn-dl/issues/9#issuecomment-518099891 solved the issue.
